### ISSUE TITLE
New version of react navigation does not fit RNSE

### ISSUE THREAD

**Issue by sa8ab** [IjzerenHein/react-native-shared-element#15]
Hi, Thank you for your great lib,
there seems to be new version of react navigation in which the lib does not work and gives errors. will be thankful if you check that out and fix it.
Tried using react native magic move instead, but it had a little bug like the image/view in the destination screen was visible for like a frame or so ( with react navigaiton's stack navigator ).

**Comment by IjzerenHein** [comment]
Which versions of react-navigation and react-navigation-stack are you using?
