### ISSUE TITLE
How can I force iOS version on android and edit iOS version?

### ISSUE THREAD

**Issue by juriuschakow** [IjzerenHein/react-native-shared-element#16]
Hi!
How can I force the iOS version (since it looks way better imo) on android?

I want to insert some icons on the cards, am I allowed to do that? is that possible? or will I crash it maybe somehow?

Thank you very much!! Your library is crazy awesome!!!

**Comment by IjzerenHein** [comment]
Hi!

> How can I force the iOS version (since it looks way better imo) on android?

> I want to insert some icons on the cards, am I allowed to do that? is that possible? or will I crash it maybe somehow?

I don't understand, what is it you are trying to do?

> Thank you very much!! Your library is crazy awesome!!!

Thanks :)

**Comment by juriuschakow** [comment]
Hi! Thank you so much for your fast reply!
The UI has two different looks, one look for iOS (cupertino), and one for Android (Material Design).
I want to use cupertino (iOS) design also on android. Because it looks much better for me. Is that possible?

I want to insert these icons/views/buttons on the cards. Is that somehow possible?
![image](https://user-images.githubusercontent.com/45340729/74612354-ead88980-5104-11ea-989c-34f92c622e9b.png)

Thank you some much!! Saitama-sensei would be proud of you

**Comment by IjzerenHein** [comment]
Oh you mean the demo. Ehm, well I guess you can fork the project and modify the app in the Example folder. All the code is in there.

**Comment by juriuschakow** [comment]
No no I don't want to use the demo. I want to integrate the library into my own project. Is it possible to insert my icons on the cards?

If I fork it, I won't have the ability anymore to update it right?

**Comment by IjzerenHein** [comment]
The cards are part of the Example app. The only thing that the lib itself exposes and the things mentioned in the API documentation:
https://github.com/IjzerenHein/react-native-shared-element#api-documentation

**Comment by juriuschakow** [comment]
Thank you very much you are awesome!! 

My big start-up is ready in 12 to 16 months. you definitely saved me now a big amount of time, thank you very much for this library!! When I get big revenue I want to give you a big donation!! thanks for open sourcing this awesome library!!

**Comment by IjzerenHein** [comment]
Haha, thank you so much, wish you all the luck with the start up 😄
