### ISSUE TITLE
Container views with a transform property causing incorrect measurement

### ISSUE THREAD

**Issue by ajsmth** [IjzerenHein/react-native-shared-element#18]
Hey there - thanks so much for this library. I've tried to do this kind of thing on the JS side and it's never been quite as nice as this. 

I've run into an issue where when a container view has any kind of X or Y transformation, the measurements appear to be taken from the layout of the containing view before it is transformed, meaning the overlay doesn't line up with what's actually on screen. My understanding is that transforms are applied after layout and perhaps this is causing the issue

I've taken two demo videos to demonstrate

Without containing transform:
![shared-element-standard](https://user-images.githubusercontent.com/40680668/76644372-7da9ef80-651c-11ea-9b0b-7776110eb42b.gif)

With containing transform:
![shared-element-transform-bug](https://user-images.githubusercontent.com/40680668/76644387-81d60d00-651c-11ea-9733-4b89a639c103.gif)

I'm wondering if theres anything that can be done about this - I've uploaded a sample repo as well in case you wanted to take a look: https://github.com/ajsmth/shared-elements-transition-transform

**Comment by ajsmth** [comment]
After taking a look, I think it is these two lines here that seem to remove the transforms applied on the container style: https://github.com/IjzerenHein/react-native-shared-element/blob/master/ios/RNSharedElementTransition.m#L236-L237

I'm not sure what they do other than that, or if this breaks anything

**Comment by ajsmth** [comment]
Looks like a similar adjustment is made on Android: https://github.com/IjzerenHein/react-native-shared-element/blob/master/android/src/main/java/com/ijzerenhein/sharedelement/RNSharedElementNode.java#L200-L201

Although from the comment it seems like the reason has something to do with a translation from the navigator, it seems to keep the transition layer positioned in the center of the screen?

**Comment by IjzerenHein** [comment]
Hi! I'm still investigating this but it looks like that this happens when the ancestor-view has a transform applied to to, and it translated X pixels down. Can you confirm that your ancestor view is translated ?
I could not reproduce this when applying a translate transform on the shared-element itself.

**Comment by ajsmth** [comment]
hey there - yup it's on the ancestor view, or any ancestor view really. i've forked this and fixed it for my use case but i can submit a PR if you are interested!

**Comment by IjzerenHein** [comment]
Hey!
I've already fixed it, both for iOS and Android (which was also affected). I'm curious how you fixed it though?

**Comment by IjzerenHein** [comment]
Also wanted to say that that's some pretty sweet Navigator that you build there. 🚀Are you planning on open sourcing it?

**Comment by ajsmth** [comment]
awsome! removing the two lines i referenced seemed to fix it for iOS, for android i had to mess with some of the measurements since i think the relative layout seems to funky - you can see here if curious: https://github.com/ajsmth/earhart-shared-element/commit/5ac9e9cdd60a140e0437dea1252d5a57e486dd78

**Comment by ajsmth** [comment]
> Also wanted to say that that's some pretty sweet Navigator that you build there. 🚀Are you planning on open sourcing it?

ya! https://github.com/ajsmth/shared-element-rn
its also a new add on for my routing library: https://github.com/ajsmth/shared-element-rn

**Comment by IjzerenHein** [comment]
> awsome! removing the two lines i referenced seemed to fix it for iOS, for android i had to mess with some of the measurements since i think the relative layout seems to funky - you can see here if curious: [ajsmth/earhart-shared-element@5ac9e9c](https://github.com/ajsmth/earhart-shared-element/commit/5ac9e9cdd60a140e0437dea1252d5a57e486dd78)

Ah I see. Yeah those were needed otherwise right-to-left navigator translations are broken.😅

**Comment by ajsmth** [comment]
i sort of figured from the comments that this was intentional

**Comment by IjzerenHein** [comment]
> ya! https://github.com/ajsmth/shared-element-rn
its also a new add on for my routing library: https://github.com/ajsmth/shared-element-rn

Nice man, looks awesome!!

**Comment by IjzerenHein** [comment]
Just released a new version with the fixes:
https://github.com/IjzerenHein/react-native-shared-element/releases/tag/v0.6.0

Let me know whether it solves your problem?

**Comment by ajsmth** [comment]
looks like it works great on iOS, but I'm having the same issues on android unfortunately, trying to figure out whats going on if maybe i need to update my own implementation

**Comment by IjzerenHein** [comment]
Hmm interesting. For it to work correctly both the start- and end- ancestor need to be at the same location. Is this the case?

**Comment by ajsmth** [comment]
okay so it looks like the debug overlay was incorrect, but the actual transitions seem to be working!

**Comment by ajsmth** [comment]
awesome, this is working great -- thanks so much!

**Comment by IjzerenHein** [comment]
> okay so it looks like the debug overlay was incorrect, but the actual transitions seem to be working!

Ah of course, I forgot to update the code in the `measure` event which powers the debug overlay.
Great find, will fix!

> awesome, this is working great -- thanks so much!

Awesome, glad it's working now 😊

**Comment by IjzerenHein** [comment]
Released https://github.com/IjzerenHein/react-native-shared-element/releases/tag/v0.6.1 which (should) fix the debug overlays on Android as well. Let me know whether it works.
cheers!
