### ISSUE TITLE
Animated.Image does not animate correctly

### ISSUE THREAD

**Issue by rpander93** [IjzerenHein/react-native-shared-element#2]
Hey,

Thanks for the great work! I'm experimenting with this library and i found out that using an <Animated.Image /> as child of a <SharedElement /> doesnt seem to work. Changing it to a regular <Image /> works. 

Are you aware of this issue and are you planning to fix this?

Again, many thanks!

**Comment by IjzerenHein** [comment]
Hey! I guess "oops" is the correct response here. I have to admit, I did to add a test for this, so I guess this could indeed not work. Are you seeing issues on both iOS and Android?

**Comment by rpander93** [comment]
I tested this on iOS using Expo and the Expo app crashes on navigation. I will test on Android asap.

**Comment by rpander93** [comment]
Created a snack here: https://snack.expo.io/@rpander93/shared-element-crash

It works as long as the Animated.Image does not have a transform. As soon as it does, it crashes on navigate. Tested on both iOS and Android

**Comment by IjzerenHein** [comment]
Hi. I've found and fixed the problem. The fix currently sits on master and I expect to release a new version within a couple days.

**Comment by rpander93** [comment]
Great! Thanks for the effort.

**Comment by IjzerenHein** [comment]
Fixed in v0.5.2: https://github.com/IjzerenHein/react-native-shared-element/releases/tag/v0.5.2
