### ISSUE TITLE
Image resize problem

### ISSUE THREAD

**Issue by diegodls** [IjzerenHein/react-native-shared-element#21]
Hi guys, what's up?
So, i have using it to get a gorgeous transition effect, and it's a nice module, but i have this problem when i tried to reduce a image to fit in a <View>
The first component is a MainScreen.js whit a list where my image is, the when i click in that component, my image should reduce a bit and fit into a rounded element in Details.js, but the image glitch before resize, but when i expand my image again in FullScreen.js, i have no problem at all, only when i try to fit a image in a element.
It's a problem with my code, react native rendering or the module?
Thanks for your time making this awesome module, and for helping.

Code:
[https://github.com/diegodls/deputados_api_react_native/tree/master/src/screens](https://github.com/diegodls/deputados_api_react_native/tree/master/src/screens)

Exemple:
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/41457134/77828687-affe4400-70fb-11ea-9362-5a785084c258.gif)

**Comment by IjzerenHein** [comment]
Hi! 👋 In order for image transitions to work perfectly, you need to restructure your code so that `<Image>` is a direct child of `<SharedElement>`.

**Comment by diegodls** [comment]
Humm, i get it, i tried so many ways to find a workaround to this problem and is that simple. I already tried this form, making a `<Image>` child of `<SharedElement>`, but, some proprieties/styles was breaking the effect, now it's working perfectly.
Thanks again for your answer/helping.

**Comment by IjzerenHein** [comment]
Glad it worked!

**Comment by TheGreatFellow** [comment]
>  but, some proprieties/styles was breaking the effect, now it's working perfectly.
@diegodls I'm facing the same issue and I've tried many things, but nothing seems to work 
Can you specify which of the proprieties and styles was causing this?

**Comment by TheRafaelFarias** [comment]
Facing the same issue, on both screens the `<Image />` is a direct child of `<SharedElement />`

**Comment by paul12p-pichincha** [comment]
any update?
