### ISSUE TITLE
Can it be used with react-native-router-flux?

### ISSUE THREAD

**Issue by marlonfrr** [IjzerenHein/react-native-shared-element#27]
Hello! Hope you're doing well.

I have a question since I was looking for a way to achieve this shared element transitions, I already realized that you have a library that natively binds with react-navigation, the problem is that I use react-native-router-flux instead. Is it possible to achieve this transition with react-native-shared-element even if I use other router libraries (like rnrf)? If so, I don't understand how to get these nodes into SharedElementTransition component props since screens are located in different files. I feel a bit lost😅.

Thanks in advance.

**Comment by IjzerenHein** [comment]
Hi! I guess this could be implemented. As RNRF is based on react-navigation most of the things implemented in `react-navigation-shared-element` should just work.
The only thing is that you'll need to create a custom `Stack` component that uses `createSharedElementStackNavigator` internally.

Such a thing should probably be released as a separate package that uses `react-navigation-shared-element` as a dependency.

**Comment by roots-ai** [comment]
Is it possible for you to share a sample code that we can use with RNRF?

**Comment by roots-ai** [comment]
Any updates here?
