### ISSUE TITLE
react-navigation-shared-element has been ignored!!

### ISSUE THREAD

**Issue by AnasAlamin** [IjzerenHein/react-native-shared-element#35]
my project for some reason is ignoring the package.
PS. there was an internal error inside the package in node_modules and i fixed it after installing multiple other packages.

    "@react-navigation/native": "^5.0.9",
    "@react-navigation/stack": "^5.1.1",

== complete log below ==
`warn Package react-navigation-shared-element has been ignored because it contains invalid configuration. Reason: Cannot find module 'react-navigation-shared-element\package.json'
Require stack:
- C:\Users\User\menu-app\node_modules\react-native\node_modules\@react-native-community\cli\build\tools\config\resolveNodeModuleDir.js
- C:\Users\User\menu-app\node_modules\react-native\node_modules\@react-native-community\cli\build\tools\releaseChecker\index.js
- C:\Users\User\menu-app\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\server\runServer.js
- C:\Users\User\menu-app\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\server\server.js
- C:\Users\User\menu-app\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\index.js
- C:\Users\User\menu-app\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js
- C:\Users\User\menu-app\node_modules\react-native\local-cli\cli.js`

**Comment by IjzerenHein** [comment]
Please point out which part of react-native-shared-element do you think contains an error.
More likely, something is probably wrong with your setup or caches and it has nothing to do with RNSE ;)
