### ISSUE TITLE
RNSharedElementTransition is not available

### ISSUE THREAD

**Issue by prrrcl** [IjzerenHein/react-native-shared-element#37]
Im using react-native-cli project. Im using react-navigation 5 and your prerelease tag.

when i use Expo, i havent got any problem, but on Shared screen this message appear: `RNSharedElementTransition is not available, did you forget to link `react-native-shared-element` into your project?`

is a bug? i linked manually but i havent got nothing

**Comment by nicoache1** [comment]
Same issue happens to me with a vanilla React-Native app. Check in Xcode and it seems that the library is installed in the pods.

**Comment by IjzerenHein** [comment]
Hi, please provide a full repo containing the exact steps that you performed.
Most likely, the project is not linked correctly into your XCode workspace.

**Comment by prrrcl** [comment]
> Same issue happens to me with a vanilla React-Native app. Check in Xcode and it seems that the library is installed in the pods.

Yeah, it is installed :/

**Comment by KochMario** [comment]
Not sure if it helps, but I initially had the same problem and warning message on androd.
For me personally it was due to another error in my build process, that's why android was never built successfully after I added react-native-shared-element.
Once I fixed the other (unrelated) build error, the build process succeeded and react-native-shared-element was linked / included correctly.
(I'm using react-navigation 5 and the rreact-navigation-shared-element prerelease as well.)

Does your error appear on android or ios?

**Comment by BATTLEROYALXS** [comment]
Same problem here ! :(

**Comment by Alarees** [comment]
a'm having the same issue here.

- "react-native-shared-element": "^0.7.0"
- "react-navigation-shared-element": "^5.0.0-alpha1"   // pre-release
- react-navigation 5

**Comment by Alarees** [comment]
i solve the problem :

1. `react-native link react-native-shared-element` 
> `optionally link when needed`  as in `README`
2. re-build the code `npx react-native run-android`

**Comment by longtq-younet** [comment]
I solve the problem: 
go to Podfile -> Add pod 'RNSharedElement', :path => '../ios/node_modules/react-native-shared-element'

**Comment by IjzerenHein** [comment]
It looks like the code is not linked correctly. On React Native 0.59 or lower the native code needs to be linked manually. Wither by using `react-native link react-native-shared-element` or by manually updating the `ios/Podfile` and the Android project.
As of React Native 0.60, linking is performed automatically.

**Comment by amirbhz86** [comment]
I think it is because install wrong module 
remove all modules include react navigation and react navigation share elements
then install them again

dont forget to "pod install" in ios directory

**Comment by MarcHbb** [comment]
I have the same issue with expo, using react navigation v6

**Comment by robhern135** [comment]
This is still an issue in expo with react navigation 6

**Comment by HenZzz-999** [comment]
This problem has a "solution" but it is not the best, I transferred my SDK 49 expo project to SDK 48 and noticed that in the versions of 'react-navigation' compatible with SDK 48 it works correctly and does not cause problems.

The developer says that he has a solution by placing the import that StackNavigator creates for the dependency in the following way:
`import { createSharedElementStackNavigator } from 'react-navigation-shared-element/build/v4';`

Apparently, in that route, version 4 of the dependency is imported, which is compatible, but it didn't work for me, the following error appeared:
```
[Error: undefined Unable to resolve module react-navigation-stack ---> (the error path appears here)
2 | import * as React from "react";
   3 | import { Platform } from "react-native";
> 4 | import { createStackNavigator, CardAnimationContext, } from "react-navigation-stack";
     | ^
   5 | import SharedElementRendererContext from "../SharedElementRendererContext";
   6 | import SharedElementRendererData from "../SharedElementRendererData";
   7 | import { SharedElementRendererProxy } from "../SharedElementRendererProxy";]
```

Apparently this is important in the incorrect dependency on 'react-navigation/stack'.

This would be my contribution a little long but I wanted to help with the information to see if the problem could be solved :).

**Comment by joelsoncastro** [comment]
I am also having this issue in expo this is my dependency list:

 "dependencies": {
    "@react-navigation/bottom-tabs": "^6.5.11",
    "@react-navigation/material-top-tabs": "^6.6.5",
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/stack": "^6.3.20",
    "@types/react": "~18.2.14",
    "expo": "~49.0.15",
    "expo-status-bar": "~1.6.0",
    "ms": "^2.1.3",
    "react": "18.2.0",
    "react-native": "0.72.6",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-pager-view": "^6.2.2",
    "react-native-reanimated": "~3.3.0",
    "react-native-safe-area-context": "^4.7.3",
    "react-native-screens": "~3.22.0",
    "react-native-scrollable-tab-view": "^1.0.0",
    "react-native-svg": "^13.14.0",
    "react-native-svg-transformer": "^1.1.0",
    "react-navigation-shared-element": "^3.1.3",
    "typescript": "^5.1.3"
  },

**Comment by melnikovkolya** [comment]
@joelsoncastro 

Since you are using expo version >49, the `react-native-shared-element` is still available, but you need to run `expo run:ios/android`, since it only works in the development builds. 

E.g., there is this note at the header of the page https://docs.expo.dev/versions/v48.0.0/sdk/shared-element/

`In SDK 49 and higher, this library will no longer be available in [Expo Go](https://docs.expo.dev/get-started/expo-go). You can still use it with [development builds](https://docs.expo.dev/develop/development-builds/introduction).`

**Comment by joelsoncastro** [comment]
Hi @melnikovkolya,

You are right. I was using the Preview Build, assuming it was the same thing. I had a go at it today and it worked straight ahead. 

Thank you very much

**Comment by jakeherm** [comment]
I am having this same issue. How were people able to solve it?
