### ISSUE TITLE
Error when building test-app

### ISSUE THREAD

**Issue by dirkpostma** [IjzerenHein/react-native-shared-element#38]
**Actions**
When I perform following actions:

```
git clone https://github.com/IjzerenHein/react-native-shared-element
cd react-native-shared-element
yarn
cd test-app
yarn
cd ios; pod install; cd ..
yarn ios
```

**Actual result**
I get the following error:

```
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually:
  - react-native-shared-element (to unlink run: "react-native unlink react-native-shared-element")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
```

**Expected result**
I would expect the iOS simulator start and run the example app.

**Relevant information**
Output of `yarn react-native info`:

```
System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.14 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.14.2 - /var/folders/p8/lc8f03hj4glfwjx1c0_39d8w0000gn/T/yarn--1598889724703-0.40924107565290346/node
    Yarn: 1.22.4 - /var/folders/p8/lc8f03hj4glfwjx1c0_39d8w0000gn/T/yarn--1598889724703-0.40924107565290346/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.14.2/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 19, 23, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.0
      System Images: android-19 | Google APIs Intel x86 Atom, android-21 | Intel x86 Atom, android-21 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.9.0 => 16.9.0
    react-native: ~0.61.4 => 0.61.5
```

**Comment by IjzerenHein** [comment]
Hmm, interesting. I'm in the process of updating the example app, and it's building fine to me tbh. The test-app is now in the `./example` folder and updated to Expo SDK 42 (bare).

> error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually:
  - react-native-shared-element (to unlink run: "react-native unlink react-native-shared-element")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.

I believe that is just a warning and shouldn't stop the build from continuing. There probably was a different problem causing the build to stop. Please try again with the current code and let me know if the build still fails and with what error

**Comment by IjzerenHein** [comment]
Closing. Feel free to re-open with additional info if this problem still persists
