### ISSUE TITLE
cp: ./build/index.js.flow: No such file or directory

### ISSUE THREAD

**Issue by joshua-augustinus** [IjzerenHein/react-native-shared-element#43]
Clone repo then run yarn at root directory

Error:
```
cp: ./build/index.js.flow: No such file or directory
```

yarn 1.22.10
node 14.15.0

**Comment by longtq-younet** [comment]
add folder build in root directory

**Comment by IjzerenHein** [comment]
Thanks for reporting, problem has been fixed in dda30653f6097b950bb98c12cc578cc4baff5344
Closing this issue. Feel free to re-open if the problem still persists.
