### ISSUE TITLE
Random iOS Crashes: Thread 1: EXC_BAD_ACCESS (code=EXC_I386_GPFLT)

### ISSUE THREAD

**Issue by ksitko** [IjzerenHein/react-native-shared-element#45]
### Description
I'm experiencing random crashes in the iOS simulator when using `react-native-shared-element` in conjunction with `react-navigation-shared-element`. I have a shared element which contains a Text component which I scale using a scale transform style. This works great but every so often, without warning, my app crashes with a `Thread 1: EXC_BAD_ACCESS (code=EXC_I386_GPFLT)` error.

### Screenshots
<img width="1379" alt="Screen Shot 2020-12-10 at 1 35 42 PM" src="https://user-images.githubusercontent.com/13754630/101815502-a122ba80-3aed-11eb-9fb5-20eb4d28468e.png">

## Package versions
```
react-native-shared-element@0.7.0
react-navigation-shared-element@^5.0.0-alpha1
```
```
  Expo CLI 4.0.5 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 14.4.0 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.2 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: 0.63.2 => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.13 
    Expo Workflow: bare
```

**Comment by IjzerenHein** [comment]
Hi, and thanks for reporting. This issue has been fixes in 076572b308cc134edbb0bbf765da92817e4be0a6
and released as part of v0.8.0:
https://github.com/IjzerenHein/react-native-shared-element/releases/tag/v0.8.0

I'm going to close this issue. Feel free to re-open with additional info if the problem still persists 👍
