### ISSUE TITLE
cant find navigation-v5 branch for shared element

### ISSUE THREAD

**Issue by Saad9624** [IjzerenHein/react-native-shared-element#47]
is it remove or under development ??

**Comment by gorbypark** [comment]
Are you looking for `react-navigation-shared-element`?  There's a seperate package which has alpha support for react-navigation v5 in the @next version (ie: `yarn add react-native-shared-element react-navigation-shared-element@next`).

**Comment by abumalick** [comment]
https://github.com/IjzerenHein/react-navigation-shared-element/blob/master/README-prerelease.md
