### ISSUE TITLE
can not understand how to use this lib

### ISSUE THREAD

**Issue by KingAmo** [IjzerenHein/react-native-shared-element#49]
is there a basic example to show how to use this lib with `react navigation v5` ?

**Comment by gorbypark** [comment]
[Here's a decent one.](https://blog.logrocket.com/how-to-use-shared-element-transition-with-react-navigation-v5/)

**Comment by KingAmo** [comment]
> [Here's a decent one.](https://blog.logrocket.com/how-to-use-shared-element-transition-with-react-navigation-v5/)

thanks a lot, i will try
