### ISSUE TITLE
Since 0.61.1, borderRadius / image resize doesn't work properly

### ISSUE THREAD

**Issue by reimertz** [IjzerenHein/react-native-shared-element#5]
Hi there, first, thanks for working on this! I am super excited to animate our new app in new ways! :D 

Your Example app was working fine, but when you updated from `0.59.9` to `0.61.1` seems to have borked the border radius animation + image animations (they are getting skewed when you do the Card 2 animations).

I had the same issue since I started with 0.61.1 from the beginning. First I thought it was my own bad, but you getting the same issues confirm this is something related to React Native. 

I have spent some time and I think the reasons because of this commit: https://github.com/facebook/react-native/commit/3b67bfab1ed8f2a4cede4e58b41a8b11c63ab484

I'm trying to figure out what code that might have borked it, but I'll add this ticket here if someone else would like to help.

**Comment by reimertz** [comment]
@IjzerenHein any idea what could be causing this? <3

**Comment by IjzerenHein** [comment]
Heyyy! Sorry, I've not gotten around to look into this yet. First of all, are you seeing this on iOS, Android or both? I hope to get back working the shared element transitions somewhere in the next two weeks.

**Comment by reimertz** [comment]
No worries at all! I don't know about Android, I mainly develop for iOS right now.

I'm currently running the tests you wrote in the `Example` app. Everything related to a border breaks both views and images. borderRadius works on views, but not on images. 

I wonder if it could be related to https://github.com/facebook/react-native/issues/26627?

**Comment by reimertz** [comment]
Hello, after some more investigation, it seems that react-native itself doesn't have any issues properly animating both borderRadius, borderWidth and borderColor at the same time. 

![Screen Recording 2019-10-30 at 14 02 35 mov_ZWDiMFxR](https://user-images.githubusercontent.com/625287/67841834-efaa0b00-fb1e-11e9-8349-972c2ada41f9.gif)

I'm going to try and deep dive into your code on the iOS side of things but I'm worried I might not be able to figure this one out do to the complexity of your code 😅

**Comment by IjzerenHein** [comment]
Alright, good thing you investigated that!

Could you also share a video/gif of the crooked shared-element transition?

**Comment by reimertz** [comment]
Sadly, all of them are borken running on device. No image properly scales anymore seeing stretched images on every transition.

**Comment by yolpsoftware** [comment]
There are also issues on the simulator, especially with image scaling:

![shared-elements-issue-5](https://user-images.githubusercontent.com/1302357/68017888-163f8180-fc98-11e9-93b3-ae4a0606ef0f.gif)

`borderRadius` seem to work properly though (but not on the device).

**Comment by reimertz** [comment]
Thanks @yolpsoftware for helping out. I’m trying to understand iOS implementation but I’m moving along quite slow. 

Not giving up though, I’m building a new MVP for my startup and I have decided this to be a main part of our new way transition between views. So hyped to create a beautiful app! :D

**Comment by reimertz** [comment]
It’s funny; if you’re on latest messenger and open image. Look at the border radius! They seem to have the same issue I am seeing but in production. I feel like some weird, pretty substantial bug being introduced in 0.60.*

**Comment by yolpsoftware** [comment]
You mean Facebook messenger? I'm not using it, so I can't confirm it.

Open a bug with them, maybe they have the resources to fix the bug soon.

**Comment by reimertz** [comment]
That is a good idea! Hopefully they share the same assumptions shared-elements do as wells

**Comment by IjzerenHein** [comment]
Alright, thanks for the input guys. I've had a busy period and also moved to a new house. I'm expecting to pick up shared-element related issues within the next 2 weeks. Hang in there.

**Comment by reimertz** [comment]
Don’t worry dude and congrats on the new house! If I were around I’d offer moving help haha! :D

**Comment by IjzerenHein** [comment]
Thanks! Be careful, I might take you up on that ;)

**Comment by IjzerenHein** [comment]
I've did some research and have found that RCTImage on iOS has been changed to no longer be inherited from UIImageView, but from RCTView. This is causing problems with border-radius animations and with access of the underlying image (causing stretching effects). This change was introduced in RN 0.61.4.
https://github.com/facebook/react-native/commit/51990014eb1afebb74c6049753acbad94109deb0#diff-0043b718537f370024c31c28240de5a9

I'm going to take a closer look and see whether I can fix it.

**Comment by IjzerenHein** [comment]
Hi. I've found and fixed the problems regarding RN 0.61. The fixes currently reside on master and I expect to release a new version within a couple days.

**Comment by reimertz** [comment]
Hey there, just looked at all your commits. Amazing work! Seriously can you please add sponsor feature to this repo so I can start sponsor you?

**Comment by IjzerenHein** [comment]
Hi. I've released the new version that fixes this problem, v0.5.2.
https://github.com/IjzerenHein/react-native-shared-element/releases/tag/v0.5.2

Apparently, the breaking change was introduced in RN 0.60. It's baffling how it went unnoticed for so long. Anyhow, it's fixed now!
