### ISSUE TITLE
Warning: Unexpected pop

### ISSUE THREAD

**Issue by TheChanDI** [IjzerenHein/react-native-shared-element#50]
This error runs continuously and crashes the app for android.
In iOS, it is working fine.

**Comment by ghadeeraqraa1992** [comment]
The same issue

**Comment by IjzerenHein** [comment]
Please provide more context, or an example app that exhibits this problem.
Closing this as too little information is provided.
Feel free to re-open with additional info on how to reproduce or where the error occurs.
