### ISSUE TITLE
[typescript] missing id in types

### ISSUE THREAD

**Issue by troZee** [IjzerenHein/react-native-shared-element#56]
![Screenshot 2021-04-27 at 15 32 55](https://user-images.githubusercontent.com/12766071/116250546-1a097280-a76e-11eb-822a-c65266860f54.png)

**Comment by nandorojo** [comment]
I believe this is only in the navigation library

**Comment by IjzerenHein** [comment]
I believe you are trying to use the react-navigation binding. It's slightly confusing but both `react-native-shared-element` and `react-navigation-shared-element` export a `SharedElement` component. The one in `react-navigation-shared-element` extends the original one and allows you to specify an `id` which is then used by `createSharedElementStackNavigator`. You are most likely importing it from `react-native-shared-element` directly, so change your import to this:

```tsx
import { SharedElement } from 'react-navigation-shared-element';
```

**Comment by IjzerenHein** [comment]
Closing this issue. Feel free to re-open with additional info if you feel this problem is insufficiently answered.
