### ISSUE TITLE
Is this compatible with @react-navigation/stack (react-navigation v5)

### ISSUE THREAD

**Issue by anfen** [IjzerenHein/react-native-shared-element#7]
I've run the example project under ./Example, and the [https://github.com/IjzerenHein/react-navigation-shared-element-rn60demo](react-navigation-shared-element-rn60demo), but could do with a code snippet or advice for a bleeding edge @react-navigation/stack v5 implementation.

**Edit:** This may belong here on second thoughts: [https://github.com/IjzerenHein/react-navigation-shared-element](react-navigation-shared-element) Is v5 support far off?

**Comment by IjzerenHein** [comment]
Hey! Yes that's right, this should be at the react-navigation-shared-element repo.
I'm hoping to get back to shared-element development within the next two weeks, in which I'm also gonna pick up the v5 release.

**Comment by anfen** [comment]
Great. Look forward to it. Excellent work.

**Comment by sunnylqm** [comment]
Can we reopen this issue and track the progress and blockers? @IjzerenHein

**Comment by IjzerenHein** [comment]
There are currently no blockers on the native side for this. You are probably referring to the react-navigation binding. You can track the progress here:
https://github.com/IjzerenHein/react-navigation-shared-element/issues/2

**Comment by sunnylqm** [comment]
Ah right, thanks
