### ISSUE TITLE
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined

### ISSUE THREAD

**Issue by longtq-younet** [IjzerenHein/react-native-shared-element#70]
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `RouterScreenTransition`.

**Comment by IjzerenHein** [comment]
I'm assuming you're trying to run the `example` app, is that correct? You might need to run `yarn build` in the root folder to update the build files.
Also, I've just completed updating the example app and its instructions, you can find them here:
https://github.com/IjzerenHein/react-native-shared-element/tree/main/example

I'm going to close this issue, but feel free to re-open it with additional info if the problem still persists.
