### ISSUE TITLE
Incorrect position of SharedElement in inverted Flatlist

### ISSUE THREAD

**Issue by waroulolz** [IjzerenHein/react-native-shared-element#72]
Hi,
I have an shared element image displayed in each item of my flatlist. On click it transitions nicely to another view with the same shared element image.

However, if I add inverted={true} to my flatlist, the transition animations doesn't happen... while the debug mode is showing the correct start/end nodes.

```
<FlatList
        data={listData}
        initialNumToRender={6}
        renderItem={renderItem}
        keyExtractor={(item) => item.uuid}
        inverted={true}
      />
```

**Comment by IjzerenHein** [comment]
As far as I'm aware, this problem affects the Android implementation. The layout for inverted ScrollViews is not obtained correctly causing weird position and clipping issues.

**Comment by p-syche** [comment]
This issue has been open a while ago. I checked it today in the example app and I couldn't see the bug.
@waroulolz can you take a look at the video and let me know if that's the expected behavior?

https://user-images.githubusercontent.com/4152181/214843722-d43dbee3-ecde-4fba-ae64-3169689e499e.mp4

**Comment by p-syche** [comment]
I'm closing this issue because I wasn't able to reproduce and the author is not responding.
