### ISSUE TITLE
navigation.dangerouslyGetState() has been deprecated

### ISSUE THREAD

**Issue by simonas-kralikas** [IjzerenHein/react-native-shared-element#73]
Hey,

In react-navigation v6 `navigation.dangerouslyGetState()` has been dropped and replaced to `navigation.getState().` 

Could we get some kind of patch?

Thanks.

https://reactnavigation.org/docs/upgrading-from-5.x/#dropped-dangerously-from-dangerouslygetparent-and-dangerouslygetstate

**Comment by IjzerenHein** [comment]
This is supported by the official 3.1.2 release:
https://github.com/IjzerenHein/react-navigation-shared-element/releases/tag/v3.1.2
