### ISSUE TITLE
Fails on building example app

### ISSUE THREAD

**Issue by CPhilipse** [IjzerenHein/react-native-shared-element#75]
**Actions**
When I perform following actions:

git clone https://github.com/IjzerenHein/react-native-shared-element.git
cd react-native-shared-element
yarn
mkdir build
cp ./flow-typed/index.js.flow ./build/index.js.flow
yarn build

**Actual result**
I get the following error:
D:\Mobile App Development\Work\folder\folder\react-native-
shared-element\node_modules\expo-module-scripts\bin\expo-module-build:3
set -eo pipefail
        ^^^^^^^^

SyntaxError: Unexpected identifier
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1025:15)
    at Module._compile (node:internal/modules/cjs/loader:1059:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_ma
in:79:12)
    at node:internal/main/run_main_module:17:47
error Command failed with exit code 1.

**Expected result**
I would expect it to build.

**Relevant information**
Output of yarn react-native info:
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 7.08 GB / 15.89 GB
  Binaries:
    Node: 16.4.0 - ~\AppData\Local\Temp\yarn--1629724043121-0.014450504881311943\node.CMD
    Yarn: 1.22.5 - ~\AppData\Local\Temp\yarn--1629724043121-0.014450504881311943\yarn.CMD
    npm: 7.18.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20210110.135312.0 - C:\ProgramData\chocolatey\bin\watchman.EXE
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86
Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_292 - /c/Program Files/OpenJDK/openjdk-8u292-b10/bin/javac
    Python: 3.9.6 - /c/Users/cleme/AppData/Local/Programs/Python/Python39/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.4 => 0.63.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by IjzerenHein** [comment]
Odd. `yarn build` simply executes `expo-module-scripts` which seems to fail. You could have a look [here](https://github.com/expo/expo/tree/master/packages/expo-module-scripts) but it looks like there might be something wrong with your setup

**Comment by CPhilipse** [comment]
I think you're right. When I try to add expo-module-scripts (yarn add -D expo-module-scripts) it returns the same error. Have not figured out how to fix it yet, but since it is not an issue with your project I'll close this issue. Thanks for the response!
