### ISSUE TITLE
Feature Request: Enable Sponsorship

### ISSUE THREAD

**Issue by reimertz** [IjzerenHein/react-native-shared-element#8]
For us who really appreciate all your hard work and would like to give back, plz make this repo sponsorshipable. <3

**Comment by IjzerenHein** [comment]
Haha, thanks for the support and your enthusiasm Pierre 😃
I'm working on adding sponsorring to my account and this repo :)
Appreciate it!

**Comment by IjzerenHein** [comment]
Done 😃

**Comment by IjzerenHein** [comment]
@reimertz Hey man thanks for sponsoring, appreciate it! Happy holidays and have a great Christmas!
