### ISSUE TITLE
Build fails on Android

### ISSUE THREAD

**Issue by haleyngonadi** [IjzerenHein/react-native-shared-element#83]
I'm trying to run this on the Android version of my app and I keep getting the same error: 

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/dalia/Apps/Dizilah/node_modules/react-native-shared-element/android/build.gradle' line: 3

* What went wrong:
A problem occurred evaluating project ':react-native-shared-element'.
> Plugin with id 'maven' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-shared-element'.
> com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

**Comment by IjzerenHein** [comment]
Hi! Please provide an example project (repository) which exposes this problem. Without it, it will be very difficult to fix

**Comment by DzmitrySakalouski** [comment]
Hey, is there any solution? Currently have the same error =(

**Comment by Pavelkovo** [comment]
In Gradle 7.x, the maven plugin has been removed. You should use the maven-publish plugin instead.
So, try downgrading the version. Gradle v6.9 works for me.

**Comment by IjzerenHein** [comment]
It looks like this was caused by Gradle 7 no longer supporting the maven plugin.
A new version of react-native-shared-element was released which now supports Gradle 7:
https://github.com/IjzerenHein/react-native-shared-element/releases/tag/v0.8.4

**Comment by p-syche** [comment]
I'm closing this issue as the author provided an update to the lib.

@haleyngonadi, if you're still having problems please create a new issue and link to this one, thanks!
