### ISSUE TITLE
any child of shared element , doesnt moving and staying when going back

### ISSUE THREAD

**Issue by SGamrekelashvili** [IjzerenHein/react-native-shared-element#84]
Any Solution from your side?

https://user-images.githubusercontent.com/25401990/139437886-55389ae3-1d3a-4855-b361-0883b2f42a5d.mp4

**Comment by IjzerenHein** [comment]
So little info..

I'm assuming your using react-navigation ?

I'm inclined to day that the id's are not the same on both screens.

**Comment by p-syche** [comment]
Hello @SGamrekelashvili  !

Can you provide a minimum reproductible example? It can be done through https://snack.expo.dev/ or a GitHub repo in your name.

Thanks!

**Comment by p-syche** [comment]
@SGamrekelashvili, this looks like a stale issue, so I'm closing it.
