### ISSUE TITLE
[Question]: SharedElement transition in React-Native

### ISSUE THREAD

**Issue by hristowwe** [IjzerenHein/react-native-shared-element#85]
I have a problem when i tried to trasition between two screen. I expected something like example but i got very different thing. So i have create simple design to test it but i can't figured out how can i achive final result? I will upload video. So I only added two things in my HomePage and detail page where image is located.

Here is my ShareELement in my MainPage
```
 <SharedElement id="iamge">
      <Image
      source={images.bannerBg}
      resizeMode="cover"
      style={{
      width: "100%",
      height: "100%",
      borderRadius: 20,
      }
     />
  </SharedElement>
```

Here is my ShareELement in my DetailsPage

```
 <SharedElement id={"image"}>
     <Image
      source={images.bannerBg}
      resizeMode="cover"
      style={{
      width: "100%",
      height: "100%",
      }}
      />
  </SharedElement>
```
And also i added this in my DetailsPage

```
PlantDetail.sharedElements = (route, otherRoute, showing) => [
  { id: "image", animation: "fade-in" },
];
```

My final result is 
![ezgif-7-507ad4489d61](https://user-images.githubusercontent.com/57602380/139583775-8ca55561-398a-41ae-99c7-30907867eae6.gif)

Expecter result:

![ezgif-7-1784d48109e4](https://user-images.githubusercontent.com/57602380/139583784-9d492730-4fc0-4683-9620-1f135708a30d.gif)

**Comment by siddharth-kt** [comment]
Bro spelling of your id is wrong on your MainPage.

**Comment by IjzerenHein** [comment]
Yep
