### ISSUE TITLE
Android: Does not build on RN 0.67 with Gradle 7.

### ISSUE THREAD

**Issue by andreialecu** [IjzerenHein/react-native-shared-element#87]
It appears that RN 0.67 recommends gradle 7 which removed the `maven` plugin. Ref:
https://stackoverflow.com/questions/69100888/plugin-with-id-maven-not-found

```
* What went wrong:
A problem occurred evaluating project ':react-native-shared-element'.
> Plugin with id 'maven' not found.
```

I originally saw the same error coming from `react-native-blurhash`, and bumping that one from version 1.1.5 to 1.1.8 resolved this error on that library. 

The changes made to https://github.com/mrousavy/react-native-blurhash/blob/master/android/build.gradle might serve as inspiration to fixing this problem.

Related: #83

**Comment by hugoh59** [comment]
Same issue for me
