### ISSUE TITLE
Support binding for react-native-navigation

### ISSUE THREAD

**Issue by kelvin-dev** [IjzerenHein/react-native-shared-element#88]
Dear team, we respect your work, please help Support binding for react-native-navigation,
Ref:
https://github.com/wix/react-native-navigation
Cheers,

**Comment by p-syche** [comment]
Hello @kelvin-dev,

Your comment is a duplicate of https://github.com/IjzerenHein/react-native-shared-element/issues/57 
I'll be closing this one. Please participate by adding a PR for the enhancements you'd like to see.
