### ISSUE TITLE
Multiple SharedElements in a carousel not animating on top of other SharedElements

### ISSUE THREAD

**Issue by timurridjanovic** [IjzerenHein/react-native-shared-element#92]
I have a carousel containing images. Each of these images is a SharedElement that you can swipe up to navigate to that screen. I'm having a bug where the SharedElement that is transitioning to the new screen doesn't go on top of the left and right images that are next to it. It looks a bit sloppy.
https://user-images.githubusercontent.com/1295621/154559796-29f9c8f3-fb32-4023-8744-0a84c6e2c350.mp4

**Comment by p-syche** [comment]
Hello @timurridjanovic  !

Can you provide a minimum reproductible example? It can be done through https://snack.expo.dev/ or a GitHub repo in your name.

Thanks!

**Comment by p-syche** [comment]
@timurridjanovic this looks like a stale issue, so I'm closing it.
