### ISSUE TITLE
Is there a more bare bones but complete example? Transition to full screen overlay

### ISSUE THREAD

**Issue by mfbx9da4** [IjzerenHein/react-native-shared-element#93]
The example in the readme is incomplete so I couldn't replicate. 
The examples folder has loads of examples but the router seems too complex for me to understand in a quick read.
React navigation + shared element transition example is great but doesn't support native stacks which I can't live without.

I am looking for one file which has everything I need to create a shared element transition. Could you point me to a file which has this? Thanks

I think the simplest example would be to transition an element from its original place into a full screen overlay. This should remove the need for all the complicated routing logic in the example.

**Comment by mfbx9da4** [comment]
Found this issue. https://github.com/IjzerenHein/react-native-shared-element/issues/31

Will try out the links there on Monday. Probably safe to mark as a duplicate but I think adding a link in the readme to this example would help people out thanks!

**Comment by p-syche** [comment]
Hello @mfbx9da4 !

I'm sorry to see you had trouble finding the right example 😞 
Maybe you could find some time to improve the documentation and examples? Any help is greatly appreciated!

In the meantime I'll close this issue since you found what you were looking for 💪
