### ISSUE TITLE
property is not configurable 

### ISSUE THREAD

**Issue by Bayramito** [IjzerenHein/react-native-shared-element#95]
These are the errors that i get.

<img width="833" alt="Ekran Resmi 2022-04-08 16 29 41" src="https://user-images.githubusercontent.com/44513402/162445601-275ac56a-be41-4d85-80c7-57dfbd4a074c.png">
<img width="1501" alt="Ekran Resmi 2022-04-08 16 30 02" src="https://user-images.githubusercontent.com/44513402/162445656-9e209c80-626f-49f0-b2b0-13c4068116a8.png">

This is how i handle the shared elements.
<img width="886" alt="Ekran Resmi 2022-04-08 16 30 45" src="https://user-images.githubusercontent.com/44513402/162445752-e8471914-2abf-4173-abf7-3be488a6f81f.png">

if i remove sharedElements from the detail screen, everything is working fine but transition effect of course not working

**Comment by p-syche** [comment]
Hello @Bayramito  !

Can you provide a minimum reproductible example? It can be done through https://snack.expo.dev/ or a GitHub repo in your name.

Thanks!

**Comment by p-syche** [comment]
@Bayramito this looks like a stale issue, so I'm closing it.
