### ISSUE TITLE
Transition back with gesture handler not working on IOS

### ISSUE THREAD

**Issue by MarcHbb** [IjzerenHein/react-native-shared-element#97]
In my navigator option I set : 
`options={{
                    gestureEnabled: false,
                    transitionSpec: {
                        open: { animation: "timing", config: { duration: 300 } },
                        close: { animation: "timing", config: { duration: 300 } },
                    },
                    cardStyleInterpolator: ({ current: { progress } }) => {
                        return {
                            cardStyle: {
                                opacity: progress,
                            },
                        };
                    },
                }}`
                
But if I don't mention **gestureEnabled: false**, when I'm navigating back with a tumb gesture from left to right ( go back default movement on IOS ), the transition back is not working. Instead I have a fade transition from current screen to the previous screen

**Comment by p-syche** [comment]
Hello @MarcHbb !

Can you provide a minimum reproductible example? It can be done through https://snack.expo.dev/ or a GitHub repo in your name.

Thanks!
